name: Pylint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint `ls -R|grep .py$|xargs`
        
    - name: Python quality and format checker
  # You may pin to the exact commit or the version.
  # uses: konstruktoid/action-pylint@7813e0065e5a88638bb17177d626bc2326f3a4a5
      uses: konstruktoid/action-pylint@v0.0.6
